/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import database.*;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author haydnmaneval
 */
public class workoutlogPanel extends javax.swing.JPanel {

    private int userId;

    public workoutlogPanel(int userId) {
        initComponents();
        this.userId = userId;
    }

    /**
     * Creates new form workoutlogPanel
     */
    public workoutlogPanel() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        setsField = new javax.swing.JTextField();
        volumeField = new javax.swing.JTextField();
        fatigueField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Log your workout");

        jLabel2.setText("Type of Exercise:");

        jLabel3.setText("Weight:");

        jLabel4.setText("Sets:");

        jLabel5.setText("Volume/Reps:");

        jLabel6.setText("Fatigue (1-10): ");

        volumeField.addActionListener(this::volumeFieldActionPerformed);

        saveButton.setText("Save Workout");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typeField, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(weightField)
                    .addComponent(setsField)
                    .addComponent(volumeField)
                    .addComponent(fatigueField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(setsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(volumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(fatigueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(backButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:

        homeFrame home = new homeFrame();
        home.setVisible(true);

        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        String workoutType = typeField.getText().trim();
        String setsText = setsField.getText().trim();
        String volumeText = volumeField.getText().trim(); // volume = reps
        String weightText = weightField.getText().trim();
        String fatigueText = fatigueField.getText().trim();

        if (workoutType.isEmpty() || setsText.isEmpty() || volumeText.isEmpty()
                || weightText.isEmpty() || fatigueText.isEmpty()) {

            JOptionPane.showMessageDialog(this, "All fields must be filled.");
            return;
        }
        if (userId == 0) {
            JOptionPane.showMessageDialog(this, "User not logged in properly.");
            return;
        }

        int sets, volume, weightw, fatiguelevel;

        try {
            sets = Integer.parseInt(setsText);
            volume = Integer.parseInt(volumeText); // reps stored as volume
            weightw = Integer.parseInt(weightText);
            fatiguelevel = Integer.parseInt(fatigueText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Sets, volume, weight, and fatigue must be numbers.");
            return;
        }

        try {
            Connection conn = databaseManager.getConnection();

            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Database not connected!");
                return;
            }

            String sql = "INSERT INTO workouts (workoutType, sets, volume, weightw, fatiguelevel, userId) VALUES (?, ?, ?, ?, ?, ?)";

            PreparedStatement stmt = conn.prepareStatement(sql);

            stmt.setString(1, workoutType);
            stmt.setInt(2, sets);
            stmt.setInt(3, volume); // reps stored here
            stmt.setInt(4, weightw);
            stmt.setInt(5, fatiguelevel);
            stmt.setInt(6, userId);

            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Workout saved successfully!");

            typeField.setText("");
            setsField.setText("");
            volumeField.setText("");
            weightField.setText("");
            fatigueField.setText("");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving workout.");
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void volumeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField fatigueField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField setsField;
    private javax.swing.JTextField typeField;
    private javax.swing.JTextField volumeField;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
